# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-28 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='BoardMember',
        ),
    ]
