# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-28 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_board', '0002_auto_20170928_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('position', models.CharField(help_text='(member position in the company)', max_length=250)),
                ('image', models.ImageField(upload_to='Member_ProfileImages')),
                ('slug', models.SlugField(blank=True, help_text='(will be automatically generated)', null=True, unique=True)),
                ('description', models.TextField(help_text='(member description)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
