# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-29 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_board', '0003_boardmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('evaluation', models.IntegerField(help_text='put an integer number between 0 and 100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='description',
            field=models.TextField(help_text='(member biography)'),
        ),
        migrations.AddField(
            model_name='skillsmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_board.BoardMember'),
        ),
    ]
