# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-03 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_board', '0005_auto_20170929_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='quote',
            field=models.TextField(blank=True, help_text='(member quote, optional)', null=True),
        ),
    ]
