# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-02 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name_plural': 'Image Gallery'},
        ),
    ]
