# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-02 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(company_name)', max_length=250)),
                ('slug', models.SlugField(help_text='(will be automatically generated)', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='(company description, optional)')),
                ('image', models.ImageField(upload_to='Partners_Images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
