# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-03 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, help_text='(company description, optional)', null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(help_text='(company name)', max_length=250),
        ),
    ]
