# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-25 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170925_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='(will be automatically generated)', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='(will be automatically generated)', unique=True),
        ),
    ]
