# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171012_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_views',
            field=models.IntegerField(default=0, help_text='(views number)', verbose_name='Visitors Number'),
        ),
    ]
