# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-26 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default=None, upload_to='Portfolio_Images'),
            preserve_default=False,
        ),
    ]
