# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-27 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170926_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at']},
        ),
    ]
