# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-12 11:01
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170927_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
