# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20171012_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='num_views',
            field=models.IntegerField(default=0, help_text='(views number)', verbose_name='Views Number'),
        ),
    ]
