# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-16 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20171012_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Portfolio'},
        ),
    ]
