# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-18 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(help_text='(job location)', max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
