# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20170927_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('P', 'Permanent'), ('C', 'Contract'), ('I', 'Internship')], max_length=1, null=True),
        ),
    ]
