# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('P', 'Permanent'), ('C', 'Contract'), ('I', 'Internship')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
