# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-28 08:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['last_date']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='(job description)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(help_text='(last day of application)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(help_text='<i class="(job requirements)'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='additional_information',
            field=ckeditor.fields.RichTextField(blank=True, help_text='<i class="ion-ios-information fa-lg"></i> add a cover letter or anything else you want to share', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='current_company',
            field=models.CharField(blank=True, help_text='<i class="ion-ios-information fa-lg"></i> optional', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='<i class="ion-ios-information fa-lg"></i> optional', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(help_text='<i class="ion-ios-information fa-lg"></i> resume/CV (we prefer in pdf)', upload_to='Application_Documents'),
        ),
    ]
