# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-28 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20170928_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='additional_information',
            field=models.TextField(blank=True, help_text='<i class="ion-ios-information fa-lg"></i> add a cover letter or anything else you want to share', null=True),
        ),
    ]
