# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-28 08:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20170928_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='(job description)'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
