# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-28 08:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20170928_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=ckeditor.fields.RichTextField(help_text='<i class="(job requirements)'),
        ),
    ]
