# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='(job description)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(help_text='<i class="(job requirements)'),
        ),
    ]
