# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-10 10:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20171010_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='(job description)'),
        ),
    ]
