# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-12 11:01
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20171010_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=froala_editor.fields.FroalaField(help_text='(job description)'),
        ),
    ]
